import Head from "next/head";
import Header from "./components/Header";
import TodoMain from "./components/TodoMain";


export default function Home() {

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <TodoMain />
      </main>
    </>
  );
}
